### PR TITLE
use R namespace with function merging

### PR DESCRIPTION
**Pull request by vfernandestoptal**
@bttmly  I see you also have another pull request that is very similar to this one.

This uses namespace merging to build the export definition so it exports both the factory function and the individual response functions.
I created a small sample project that shows the different ways we can import this:
https://github.com/vfernandestoptal/test-response-objects

It allows for the import syntax that you wanted for JS clients, and for TS, it depends on compiler settings, I see two ways of using it, so it would either be
```
import R from "response-objects";
```
or 

```
import * as R from "response-objects";
```

### CODE REVIEW

**Comment by vfernandestoptal** [comment]
@bttmly Configured the project to run typescript tests and copied the existing test file to typescript, so it runs tests for both javascript and typescript

**Comment by bttmly** [comment]
Awesome! Yeah my other PR I couldn't quite get it to work the way you did here. So basically we can merge this, publish a new major version, then just do a find-and-replace in API?

**Comment by vfernandestoptal** [comment]
Yes, I think so :+1:

**Comment by bttmly** [comment]
Satisfied by #12

**Pull request closed without merging**
